#ifndef LEETCODE_STRINGS_PALINDROMIC_SUBSTRINGS_CPP_SOLUTION_H_
#define LEETCODE_STRINGS_PALINDROMIC_SUBSTRINGS_CPP_SOLUTION_H_

#include <string>

int Solve(const std::string& s);

#endif  // LEETCODE_STRINGS_PALINDROMIC_SUBSTRINGS_CPP_SOLUTION_H_

