#ifndef LEETCODE_TEMPLATES_LC_TEMPLATE_QUESTION_CPP_SOLUTION_H_
#define LEETCODE_TEMPLATES_LC_TEMPLATE_QUESTION_CPP_SOLUTION_H_

#include <string>

std::string Solve(std::string input);

#endif  // LEETCODE_TEMPLATES_LC_TEMPLATE_QUESTION_CPP_SOLUTION_H_
