#ifndef LEETCODE_BIT_MANIPULATION_REVERSE_BITS_CPP_SOLUTION_H_
#define LEETCODE_BIT_MANIPULATION_REVERSE_BITS_CPP_SOLUTION_H_

#include <cstdint>

uint32_t Solve(uint32_t n);

#endif  // LEETCODE_BIT_MANIPULATION_REVERSE_BITS_CPP_SOLUTION_H_
