load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library", "rust_test")

rust_library(
    name = "reverse_bits",
    srcs = ["lib.rs"],
    crate_root = "lib.rs",
    visibility = ["//visibility:private"],
)

rust_binary(
    name = "run",
    srcs = ["main.rs"],
    deps = [":reverse_bits"],
)

rust_test(
    name = "test",
    crate = ":reverse_bits",
)
