#ifndef LEETCODE_STACKS_VALID_PARENTHESES_CPP_SOLUTION_H_
#define LEETCODE_STACKS_VALID_PARENTHESES_CPP_SOLUTION_H_

#include <string>

bool Solve(const std::string& s);

#endif  // LEETCODE_STACKS_VALID_PARENTHESES_CPP_SOLUTION_H_
