load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library", "rust_test")

rust_library(
    name = "algo_templates",
    srcs = ["lib.rs"],
    crate_root = "lib.rs",
    visibility = ["//visibility:private"],
)

rust_binary(
    name = "run",
    srcs = ["main.rs"],
    deps = [":algo_templates"],
)

rust_test(
    name = "test",
    crate = ":algo_templates",
)
