#ifndef LEETCODE_DYNAMIC_PROGRAMMING_COMBINATION_SUM4_CPP_SOLUTION_H_
#define LEETCODE_DYNAMIC_PROGRAMMING_COMBINATION_SUM4_CPP_SOLUTION_H_

#include <vector>

int Solve(const std::vector<int>& nums, int target);

#endif  // LEETCODE_DYNAMIC_PROGRAMMING_COMBINATION_SUM4_CPP_SOLUTION_H_
