#ifndef OTHER_TEMPLATES_OTHER_TEMPLATE_QUESTION_CPP_SOLUTION_H_
#define OTHER_TEMPLATES_OTHER_TEMPLATE_QUESTION_CPP_SOLUTION_H_

#include <string>

std::string Solve(std::string input);

#endif  // OTHER_TEMPLATES_OTHER_TEMPLATE_QUESTION_CPP_SOLUTION_H_
