#ifndef HACKERRANK_TEMPLATES_HR_TEMPLATE_QUESTION_CPP_SOLUTION_H_
#define HACKERRANK_TEMPLATES_HR_TEMPLATE_QUESTION_CPP_SOLUTION_H_

#include <string>

std::string Solve(std::string input);

#endif  // HACKERRANK_TEMPLATES_HR_TEMPLATE_QUESTION_CPP_SOLUTION_H_
