load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library", "rust_test")

rust_library(
    name = "merge_two_sorted_lists",
    srcs = ["lib.rs"],
    crate_root = "lib.rs",
    visibility = ["//visibility:private"],
)

rust_binary(
    name = "run",
    srcs = ["main.rs"],
    deps = [":merge_two_sorted_lists"],
)

rust_test(
    name = "test",
    crate = ":merge_two_sorted_lists",
)
